name: "RSS → Discord Notifier"

on:
  # Dispara todo dia às 09:00 BRT (12:00 UTC)
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run notifier
        env:
          DISCORD_WEBHOOK_URL:    ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_LEITOR_ROLE_ID: ${{ secrets.DISCORD_LEITOR_ROLE_ID }} # novo
          DISCORD_ROLE_ID:        ${{ secrets.DISCORD_ROLE_ID }}        # opcional (fallback)
        run: npm start
