name: "RSS → Discord Notifier"

on:
  schedule:
    - cron: '0 12 * * *'    # 9 AM BRT = 12 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Restore last link cache
        uses: actions/cache@v3
        id: cache-link
        with:
          path: last_discord_item.txt
          key: rss-discord-cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run notifier
        id: run_notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_ROLE_ID:    ${{ secrets.DISCORD_ROLE_ID }}
        run: npm start

      - name: Save last link cache
        if: steps.run_notifier.outcome == 'success'
        uses: actions/cache@v3
        with:
          path: last_discord_item.txt
          key: rss-discord-cache
