name: "RSS → Discord Notifier"

on:
  # 09:00 BRT é 12:00 UTC
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run notifier
        id: notifier
        run: npm start
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit updated cache
        if: steps.notifier.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: chore: update last_discord_item cache [skip ci]
          file_pattern: last_discord_item.txt
          branch: main
