name: "RSS → Discord Notifier"

# 1) Garanta permissão de escrita para o GITHUB_TOKEN
permissions:
  contents: write

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # … resto dos passos (Setup Node.js, Install dependencies, Run notifier) …

      - name: Commit cache de link
        if: steps.run_notifier.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_discord_item.txt
          git diff --cached --quiet || git commit -m "chore: update last_discord_item cache"
          git push origin HEAD:main
